name: Deploy Bicep IaC 6536

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template to Azure
        run: |
          az deployment group create \
            --name bicep-cicd-6536 \
            --resource-group pro6536lab18 \
            --template-file webapp-6536.bicep
